import React from 'react';
import styled from 'styled-components';

const Container = styled.div`
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
`;

const Section = styled.div`
  margin-bottom: 40px;
`;

const Title = styled.h1`
  font-size: 32px;
  margin-bottom: 20px;
`;

const Subtitle = styled.h2`
  font-size: 24px;
  margin-bottom: 20px;
`;

const Paragraph = styled.p`
  margin-bottom: 16px;
`;

const List = styled.ol`
  margin-bottom: 16px;
  padding-left: 20px;
`;

const ListItem = styled.li`
  margin-bottom: 8px;
`;

const Link = styled.a`
  color: blue;
  text-decoration: underline;
`;

const Policies = () => {
  return (
    <Container>
      <Section>
        <Title>Terms & Conditions</Title>
        <Paragraph>
          This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </Paragraph>
        <Paragraph>
          This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name <Link href="https://www.ranienterprisesballia.com/">https://www.ranienterprisesballia.com/</Link> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
        </Paragraph>
        <Paragraph>
          The Platform is owned by RANI ENTERPRISES, a company incorporated under the Companies Act, 1956 with its registered office at STATION MALGODAM ROAD, Ballia, India (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
        </Paragraph>
        <Paragraph>
          <strong>ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.</strong>
        </Paragraph>
        <Paragraph>The use of Platform and/or availing of our Services is subject to the following Terms of Use:</Paragraph>
        <List>
          <ListItem>To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration.</ListItem>
          <ListItem>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this website or through the Services, for any specific purpose.</ListItem>
          <ListItem>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner.</ListItem>
          <ListItem>The contents of the Platform and the Services are proprietary to us and are licensed to us.</ListItem>
          <ListItem>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</ListItem>
          <ListItem>You agree to pay us the charges associated with availing the Services.</ListItem>
          <ListItem>You agree not to use the Platform and/ or Services for any purpose that is unlawful or forbidden by these Terms, or Indian or local laws.</ListItem>
          <ListItem>You agree and acknowledge that the website and the Services may contain links to other third-party websites.</ListItem>
          <ListItem>You understand that upon initiating a transaction for availing the Services, you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</ListItem>
          <ListItem>You shall indemnify and hold harmless the Platform Owner and its affiliates from any claim or demand arising out of Your breach of these Terms of Use, privacy Policy, and other Policies.</ListItem>
          <ListItem>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.</ListItem>
          <ListItem>These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.</ListItem>
          <ListItem>All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Ballia and Uttar Pradesh.</ListItem>
          <ListItem>All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.</ListItem>
        </List>
      </Section>

      <Section>
        <Title>Shipping Policy</Title>
        <Paragraph>The orders for the user are shipped through registered domestic courier companies and/or speed post only.</Paragraph>
        <Paragraph>Orders are shipped within 7 days from the date of the order and/or payment or as per the delivery date agreed at the time of order confirmation.</Paragraph>
        <Paragraph>Platform Owner shall not be liable for any delay in delivery by the courier company / postal authority.</Paragraph>
        <Paragraph>Delivery of all orders will be made to the address provided by the buyer at the time of purchase.</Paragraph>
        <Paragraph>Delivery of our services will be confirmed on your email ID as specified at the time of registration.</Paragraph>
        <Subtitle>Shipping Costs</Subtitle>
        <Paragraph>If there are any shipping costs levied by the seller or the Platform Owner, the same is not refundable.</Paragraph>
      </Section>

      <Section>
        <Title>Return Policy</Title>
        <Paragraph>We offer refund/exchange within the first 7 days from the date of your purchase. If 7 days have passed since your purchase, you will not be offered a return, exchange, or refund of any kind.</Paragraph>
        <Subtitle>Eligibility for Return or Exchange</Subtitle>
        <Paragraph>In order to become eligible for a return or an exchange:</Paragraph>
        <List>
          <ListItem>The purchased item should be unused and in the same condition as you received it.</ListItem>
          <ListItem>The item must have original packaging.</ListItem>
          <ListItem>If the item that you purchased was on sale, then the item may not be eligible for a return/exchange.</ListItem>
        </List>
        <Paragraph>Only items replaced by us based on an exchange request, if found defective or damaged, are eligible for exchange.</Paragraph>
        <Subtitle>Exemptions</Subtitle>
        <Paragraph>There may be certain categories of products/items that are exempted from returns or refunds. Such categories would be identified at the time of purchase.</Paragraph>
        <Subtitle>Process for Accepted Returns/Exchanges</Subtitle>
        <Paragraph>For exchange/return accepted requests (as applicable):</Paragraph>
        <List>
          <ListItem>Once your returned product/item is received and inspected by us, we will notify you by email.</ListItem>
          <ListItem>If approved after the quality check, your request (i.e. return/exchange) will be processed as per our policies.</ListItem>
        </List>
      </Section>

      <Section>
        <Title>Refund and Cancellation Policy</Title>
        <Paragraph>This refund and cancellation policy outlines how you can cancel or seek a refund for a product/service that you have purchased through the Platform. Under this policy:</Paragraph>
        <List>
          <ListItem>Cancellations will only be considered if the request is made within 7 days of placing the order. However, cancellation requests may not be entertained if the orders have been communicated to such sellers/merchant(s) listed on the Platform and they have initiated the process of shipping them, or the product is out for delivery.</ListItem>
          <ListItem>RANI ENTERPRISES does not accept cancellation requests for perishable items like flowers, eatables, etc. However, a refund/replacement can be made if the user establishes that the quality of the product delivered is not good.</ListItem>
          <ListItem>In case of receipt of damaged or defective items, please report to our customer service team within 7 days of receipt of products.</ListItem>
          <ListItem>In case you feel that the product received is not as shown on the site or as per your expectations, you must notify our customer service within 7 days of receiving the product. The customer service team will take appropriate action after reviewing your complaint.</ListItem>
          <ListItem>In case of complaints regarding the products that come with a warranty from the manufacturers, please refer the issue to them.</ListItem>
        </List>
        <Paragraph>In case of any refunds approved by RANI ENTERPRISES, it will take 7 days for the refund to be processed to you.</Paragraph>
      </Section>

      <Section>
        <Title>Privacy Policy</Title>
        <Subtitle>Introduction</Subtitle>
        <Paragraph>This Privacy Policy describes how RANI ENTERPRISES and its affiliates (collectively "RANI ENTERPRISES, we, our, us") collect, use, share, protect, or otherwise process your information/personal data through our website <Link href="https://www.ranienterprisesballia.com/">https://www.ranienterprisesballia.com/</Link> (hereinafter referred to as Platform).</Paragraph>
        <Subtitle>Collection of Information</Subtitle>
        <Paragraph>We may collect the following information:</Paragraph>
        <List>
          <ListItem>Name, contact details, email, and payment information.</ListItem>
          <ListItem>Transactional information based on your activities on the Platform.</ListItem>
          <ListItem>Other information that you voluntarily choose to provide to us.</ListItem>
        </List>
        <Subtitle>Use of Information</Subtitle>
        <Paragraph>We may use the information for the following purposes:</Paragraph>
        <List>
          <ListItem>To provide you with our products/services.</ListItem>
          <ListItem>To personalize your experience on the Platform.</ListItem>
          <ListItem>For analytics, market research, and internal purposes.</ListItem>
          <ListItem>To comply with legal obligations.</ListItem>
        </List>
        <Subtitle>Sharing of Information</Subtitle>
        <Paragraph>We do not sell, trade, or otherwise transfer your personal information to outside parties, except as described below:</Paragraph>
        <List>
          <ListItem>With third-party vendors/service providers who assist us in operating our Platform and delivering the Services.</ListItem>
          <ListItem>To comply with legal requirements, court orders, or applicable law enforcement requests.</ListItem>
          <ListItem>In connection with a merger, acquisition, or sale of all or a portion of our business.</ListItem>
        </List>
        <Subtitle>Security</Subtitle>
        <Paragraph>We implement reasonable security measures to protect your personal information from unauthorized access, use, or disclosure.</Paragraph>
        <Subtitle>Changes to this Privacy Policy</Subtitle>
        <Paragraph>We may update our Privacy Policy from time to time. We will notify you of any material changes by posting the new Privacy Policy on the Platform.</Paragraph>
      </Section>
    </Container>
  );
};

export default Policies;
